name: Deploy MQTT Broker

on:
  push:
    branches:
      - main
    paths:
      - "scripts/**"
      - ".github/workflows/deploy.yml"

  workflow_dispatch:

env:
  EC2_HOST: 52.63.194.183 # Replace with your EC2 instance's public IP or hostname
  EC2_USER: ubuntu
  REMOTE_SCRIPT_PATH: /tmp/run-mosquitto.sh

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key
          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts

      - name: Copy run script to EC2
        run: |
          scp -i ~/.ssh/ec2_key \
            scripts/run-mosquitto.sh \
            "$EC2_USER@$EC2_HOST:$REMOTE_SCRIPT_PATH"

      - name: Run Mosquitto on EC2
        run: |
          ssh -i ~/.ssh/ec2_key "$EC2_USER@$EC2_HOST" << EOF
            chmod +x "$REMOTE_SCRIPT_PATH"
            "$REMOTE_SCRIPT_PATH"
          EOF